### ISSUE TITLE
Use StyleCI

### ISSUE THREAD

**Issue by jbrooksuk** [bu-ist/coding-standards#28]
Have you thought about using [StyleCI](https://styleci.io)? It can automatically fix your code and you can configure to your standards.

**Comment by desrosj** [comment]
Hi @jbrooksuk - we don’t handle build tools or process in this repository. However, we welcome any feedback on standards and best practices related to the languages we cover in this repository.

While we appreciate the suggestion and we are always trying out new tools, this is not really the best forum for a sales pitch.
