### ISSUE TITLE
Research: php Namespaces vs Prefixes

### ISSUE THREAD

**Issue by timkingbu** [bu-ist/coding-standards#56]
Do we care about this? Our code approaches this in different ways depending on the programmer, and often has a mix as things are copied from previous projects. 

Current guidelines favor prefixing, but also reference namespacing: https://github.com/bu-ist/coding-standards/blob/main/wordpress/README.md

And if the namespace route is taken, a method should be standardized. There are lots of opinions out there, I favor `namespace BU\Theme;`

**Comment by smtierneybu** [comment]
@hirozed @alana29s @acketon Do any of you have any commentary on this topic?  I think that this will be a good item to address and make a determination of as soon as we can and write up one or more implementation issues around it.

**Comment by acketon** [comment]
I am a big fan of of Namespacing in PHP, but sometimes it does get a bit complicated. I generally prefer it over prefixing everything especially in cases where there is similar code repeated such as registering similar metaboxes or BULP sections. 

My first real significant introduction to it was probably during the One Editorial project where namespaces were used throughout the Prepress repo. I had to contribute to some of the PHP in that plugin and I felt like it worked well and allowed us to keep function names shorter and easier to read. For instance there were multiple files that registered taxonomies for different post types or functionality. Those function names were able to be just `register_taxonomy()` as they were namespaced per file. That was easier to read for me than a long prefix like: `bu_prepress_closeup_register_taxonomy()`. 

We could probably standardize/simplify the namespacing pattern that we use to keep it from getting too verbose.

That said, I'm comfortable with either approach. I think I'd prefer namespacing but whichever direction we go I'd like to have a bit more documentation or recommended patterns/naming/etc.

**Comment by hirozed** [comment]
I would much prefer namespacing the projects over the mile-long `namespace_within_the_function_name`.  That being said, I think we should still be aware of WP core functions.  Even though the namespacing will reduce conflicts, seeing a function with the same name as core will reduce troubleshooting time.

**Comment by smtierneybu** [comment]
Do we find a happy medium, and use namespacing BUT also include BU_ at the start of function names etc to further reduce confusion?

**Comment by timkingbu** [comment]
I think maybe for functions that tie into plugins or utilities that might be good, but for theme specific functions I would rather not.

**Comment by hirozed** [comment]
> I think maybe for functions that tie into plugins or utilities that might be good, but for theme specific functions I would rather not.

Building off of that:

- Do not namespace if the functions/methods that are not being called from anywhere else (function hooks, for example)
- Namespace utility functions will be prepended with `bu_plugin` or `r_theme`
- Functions being called elsewhere will have a `use` declaration at the top of the file,  so the full namespace isn't being littered throughout the file.
- Methods that are called elsewhere in the theme/plugin will have a function which is namespaced outside the class.
  - [Example function in `r2-cfa`](https://github.com/bu-ist/r2-cfa/blob/develop/includes/class-cfa-calendar.php#L379)

**Comment by timkingbu** [comment]
Use comments in this issue to update https://github.com/bu-ist/id-gutenberg/issues/162
